### ISSUE TITLE
Filtering by MultiSelect field returns error

### ISSUE THREAD

**Issue by guillermo-t3** [Zaydme/strapi-plugin-multi-select#17]
I'm trying to use the operator $contains as $in doesn't work.

However, I get the following error from Strapi:
```
select "t0".*, "t0"."id" from "public"."articles" as "t0" where (("t0"."locale" = $1 and "t0"."featured" = $2 and "t0"."topics" like $3) and "t0"."published_at" is not null) order by "t0"."published_on" desc limit $4 - operator does not exist: jsonb ~~ unknown
error: select "t0".*, "t0"."id" from "public"."articles" as "t0" where (("t0"."locale" = $1 and "t0"."featured" = $2 and "t0"."topics" like $3) and "t0"."published_at" is not null) order by "t0"."published_on" desc limit $4 - operator does not exist: jsonb ~~ unknown
    at Parser.parseErrorMessage (/opt/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/opt/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/opt/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/opt/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

How to filter by this field?

**Comment by guillermo-t3** [comment]
Looks like it only works with `$containsi`.
Perhaps it could be included to the documentation for future reference on how to filter by this field?

Resolving.
