### ISSUE TITLE
Cannot read properties of undefined (reading 'register')

### ISSUE THREAD

**Issue by numr** [Zaydme/strapi-plugin-multi-select#5]
![企业微信截图_16728865181728](https://user-images.githubusercontent.com/13326600/210689409-a26200b9-48c8-441d-828f-44379820d8dd.png)
error: Cannot read properties of undefined (reading 'register')
TypeError: Cannot read properties of undefined (reading 'register')
    at Object.module.exports [as register] (D:\xampp\htdocs\strapi\strapi-v4\node_modules\strapi-plugin-multi-select\server\register.js:5:25)
    at Object.register (D:\xampp\htdocs\strapi\strapi-v4\node_modules\@strapi\strapi\lib\core\domain\module\index.js:47:46)
    at Object.register (D:\xampp\htdocs\strapi\strapi-v4\node_modules\@strapi\strapi\lib\core\registries\modules.js:33:19)
    at async Strapi.runLifecyclesFunctions (D:\xampp\htdocs\strapi\strapi-v4\node_modules\@strapi\strapi\lib\Strapi.js:510:5)
    at async Strapi.register (D:\xampp\htdocs\strapi\strapi-v4\node_modules\@strapi\strapi\lib\Strapi.js:379:5)
    at async Strapi.load (D:\xampp\htdocs\strapi\strapi-v4\node_modules\@strapi\strapi\lib\Strapi.js:456:5)
    at async Strapi.start (D:\xampp\htdocs\strapi\strapi-v4\node_modules\@strapi\strapi\lib\Strapi.js:198:9)

**Comment by Zaydme** [comment]
Please make sure to update Strapi v4 to a version that supports custom fields
